---

- block:
    - name: install epel-release (CentOS)
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: install httpd
      package:
        name: httpd
        state: present
        update_cache: yes
  tags:
    - install
